import { NextResponse } from 'next/server'

export async function POST(request) {
  try {
    const { content, format, filename, type } = await request.json()

    if (!content || !format) {
      return NextResponse.json(
        { error: 'Content and format cannot be empty' },
        { status: 400 }
      )
    }

    let exportContent = ''
    let mimeType = ''
    let fileExtension = ''

    switch (format.toLowerCase()) {
      case 'txt':
        exportContent = formatTextContent(content, type)
        mimeType = 'text/plain'
        fileExtension = 'txt'
        break
      
      case 'csv':
        exportContent = formatCSVContent(content, type)
        mimeType = 'text/csv'
        fileExtension = 'csv'
        break
      
      case 'pdf':
        // For PDF, we return HTML content, frontend can use libraries like jsPDF or html2pdf for conversion
        exportContent = formatHTMLContent(content, type)
        mimeType = 'text/html'
        fileExtension = 'html'
        break
      
      default:
        return NextResponse.json(
          { error: 'Unsupported export format' },
          { status: 400 }
        )
    }

    const finalFilename = filename || `${type}_${Date.now()}.${fileExtension}`

    return NextResponse.json({
      success: true,
      content: exportContent,
      filename: finalFilename,
      mimeType,
      size: new Blob([exportContent]).size
    })

  } catch (error) {
    console.error('Content export error:', error)
    return NextResponse.json(
      { error: 'Export failed, please try again' },
      { status: 500 }
    )
  }
}

function formatTextContent(content, type) {
  const timestamp = new Date().toLocaleString('en-US')
  
  switch (type) {
    case 'listing':
      return `Property Listing - ${timestamp}

${content.title || 'Property Title'}

${content.description || content}

---
Generated by ListingWriterAI Pro
Generated at: ${timestamp}`

    case 'video-script':
      if (typeof content === 'string') {
        return `Video Script - ${timestamp}

${content}

---
Generated by ListingWriterAI Pro
Generated at: ${timestamp}`
      }
      
      return `Video Script - ${timestamp}

${content.title || 'Video Script'}
Platform: ${content.platform || 'Not specified'}
Duration: ${content.duration || 'Not specified'}
Style: ${content.style || 'Not specified'}

${content.segments ? content.segments.map(segment => 
  `${segment.time} - ${segment.scene}
Content: ${segment.content}
Shooting Tips: ${segment.shootingTip}
Visual Elements: ${segment.visual}
`).join('\n') : content}

${content.tips ? 'Shooting Tips:\n' + content.tips.map(tip => `• ${tip}`).join('\n') : ''}

---
Generated by ListingWriterAI Pro
Generated at: ${timestamp}`

    case 'email':
      return `Email Content - ${timestamp}

Subject: ${content.subject || 'Email Subject'}

${content.body || content}

---
Generated by ListingWriterAI Pro
Generated at: ${timestamp}`

    default:
      return `${content}

---
Generated by ListingWriterAI Pro
Generated at: ${timestamp}`
  }
}

function formatCSVContent(content, type) {
  const timestamp = new Date().toLocaleString('en-US')
  
  switch (type) {
    case 'contacts':
      if (Array.isArray(content)) {
        const headers = ['Name', 'Email', 'Phone', 'Source', 'Import Time']
        const rows = content.map(contact => [
          contact.name || '',
          contact.email || '',
          contact.phone || '',
          contact.source || '',
          timestamp
        ])
        
        return [headers, ...rows]
          .map(row => row.map(cell => `"${cell}"`).join(','))
          .join('\n')
      }
      break
      
    case 'email-stats':
      const headers = ['Metric', 'Value', 'Export Time']
      const rows = [
        ['Total Sent', content.emailsSent || 0, timestamp],
        ['Open Rate', `${content.openRate || 0}%`, timestamp],
        ['Click Rate', `${content.clickRate || 0}%`, timestamp]
      ]
      
      return [headers, ...rows]
        .map(row => row.map(cell => `"${cell}"`).join(','))
        .join('\n')
        
    default:
      return `"Content","Type","Export Time"
"${content}","${type}","${timestamp}"`
  }
}

function formatHTMLContent(content, type) {
  const timestamp = new Date().toLocaleString('en-US')
  
  const baseHTML = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${type === 'listing' ? 'Property Listing' : type === 'video-script' ? 'Video Script' : 'Content Export'}</title>
    <style>
        body { font-family: 'Arial', sans-serif; line-height: 1.6; margin: 40px; color: #333; }
        .header { border-bottom: 2px solid #007bff; padding-bottom: 20px; margin-bottom: 30px; }
        .title { color: #007bff; font-size: 24px; font-weight: bold; margin: 0; }
        .subtitle { color: #666; font-size: 14px; margin-top: 5px; }
        .content { margin-bottom: 30px; }
        .segment { margin-bottom: 20px; padding: 15px; background: #f8f9fa; border-left: 4px solid #007bff; }
        .segment-title { font-weight: bold; color: #007bff; margin-bottom: 10px; }
        .tips { background: #fff3cd; border: 1px solid #ffeaa7; padding: 15px; border-radius: 5px; }
        .footer { border-top: 1px solid #ddd; padding-top: 20px; text-align: center; color: #666; font-size: 12px; }
    </style>
</head>
<body>`

  switch (type) {
    case 'video-script':
      if (typeof content === 'string') {
        return `${baseHTML}
    <div class="header">
        <h1 class="title">Video Script</h1>
        <p class="subtitle">Generated at: ${timestamp}</p>
    </div>
    <div class="content">
        <pre style="white-space: pre-wrap; font-family: inherit;">${content}</pre>
    </div>
    <div class="footer">
        <p>Generated by ListingWriterAI Pro</p>
    </div>
</body>
</html>`
      }
      
      return `${baseHTML}
    <div class="header">
        <h1 class="title">${content.title || 'Video Script'}</h1>
        <p class="subtitle">Platform: ${content.platform} | Duration: ${content.duration} | Style: ${content.style}</p>
        <p class="subtitle">Generated at: ${timestamp}</p>
    </div>
    <div class="content">
        ${content.segments ? content.segments.map(segment => `
        <div class="segment">
            <div class="segment-title">${segment.time} - ${segment.scene}</div>
            <p><strong>Content:</strong>${segment.content}</p>
            <p><strong>Shooting Tips:</strong>${segment.shootingTip}</p>
            <p><strong>Visual Elements:</strong>${segment.visual}</p>
        </div>
        `).join('') : `<p>${content}</p>`}
        
        ${content.tips ? `
        <div class="tips">
            <h3>Shooting Tips</h3>
            <ul>
                ${content.tips.map(tip => `<li>${tip}</li>`).join('')}
            </ul>
        </div>
        ` : ''}
    </div>
    <div class="footer">
        <p>Generated by ListingWriterAI Pro</p>
    </div>
</body>
</html>`

    default:
      return `${baseHTML}
    <div class="header">
        <h1 class="title">${type === 'listing' ? 'Property Listing' : 'Content Export'}</h1>
        <p class="subtitle">Generated at: ${timestamp}</p>
    </div>
    <div class="content">
        <div style="white-space: pre-wrap;">${typeof content === 'string' ? content : JSON.stringify(content, null, 2)}</div>
    </div>
    <div class="footer">
        <p>Generated by ListingWriterAI Pro</p>
    </div>
</body>
</html>`
  }
}